---
version: '3'
services:
  web:
    build:
      context: .
    env_file:
    - .env
    volumes:
    - .:/var/www
    ports:
    - "3000:80"
    depends_on:
    - db

  db:
    image: mariadb:11.5
    env_file:
    - .env
    volumes:
    - "db:/var/lib/mysql"
    - "./db/init-data.sql:/docker-entrypoint-initdb.d/init-data.sql"

volumes:
  db:
